### ISSUE TITLE
Updating member index in large collections

### ISSUE THREAD

**Issue by awead** [projecthydra-labs/hydra-collections#41]
[local_update_members](https://github.com/projecthydra-labs/hydra-collections/blob/master/app/models/concerns/hydra/collection.rb#L58) is called for each member in a collection.  For large collections, this ties up Fedora considerably.

To speed up things, this ought to be moved to a background job, but might be out-of-scope for this gem.

**Comment by jcoyne** [comment]
Fixed by version 5, which uses a solr join to find members.
