### ISSUE TITLE
Use atomic updates for members

### ISSUE THREAD

**Issue by awead** [projecthydra-labs/hydra-collections#43]
In `Hydra::Collection#update_member`, instead calling Fedora to reindex the entire object, just update the one field in the member's solr document with the new collection information.

Use [Spotlight's method](https://github.com/sul-dlss/spotlight/blob/dac8c7ebd9a34a05991108d746878334a108e841/app/models/concerns/spotlight/solr_document/atomic_updates.rb#L1) and add [this](https://github.com/sul-dlss/spotlight/blob/0ac59ae247051aeaaae0eb8035a10c94fb6e1de7/solr_conf/conf/solrconfig.xml#L13-L17) to the solr configuration.

**Comment by jcoyne** [comment]
Fixed by version 5 which uses a solr join to declare membership
